DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  billing_address VARCHAR(255) NOT NULL,
  shipping_address VARCHAR(255) NOT NULL,
  phone VARCHAR(255) NOT NULL
);