DROP TABLE IF EXISTS options CASCADE;
CREATE TABLE options (
  id SERIAL PRIMARY KEY NOT NULL,
  option VARCHAR(255) NOT NULL,
  price INTEGER NOT NULL,
  product_id INTEGER REFERENCES products(id) ON DELETE CASCADE
);