DROP TABLE IF EXISTS prices CASCADE;
CREATE TABLE prices (
  id SERIAL PRIMARY KEY NOT NULL,
  width INTEGER NOT NULL,
  height INTEGER NOT NULL,
  product_id INTEGER REFERENCES products(id) ON DELETE CASCADE,
  price INTEGER NOT NULL
);