DROP TABLE IF EXISTS order_li CASCADE;
CREATE TABLE order_li (
  id SERIAL PRIMARY KEY NOT NULL,
  price FLOAT,
  product_id INTEGER REFERENCES products(id) ON DELETE CASCADE,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  motor_option BOOLEAN NOT NULL DEFAULT FALSE,
  cordless_option BOOLEAN NOT NULL DEFAULT FALSE,
  retractable_cord_option BOOLEAN NOT NULL DEFAULT FALSE,
  remote_option BOOLEAN NOT NULL DEFAULT FALSE,
  metalbeadedchain_option BOOLEAN NOT NULL DEFAULT FALSE,
  outside_mount BOOLEAN NOT NULL DEFAULT FALSE,
  inside_mount BOOLEAN NOT NULL DEFAULT FALSE,
  width INTEGER,
  height INTEGER,
  is_paid BOOLEAN NOT NULL DEFAULT FALSE
);